#!/bin/sh

printbat(){
  percent=$(expr $(acpi -b | awk '{print $4}' | grep -Eo "[0-9]+"));
  if acpi | grep "Charging" > /dev/null 2>&1
  then
    echo "🔌 $percent%";
  else
    echo "🪫 $percent%";
  fi
}

printvolume() {
  vstate=$(amixer get Master | tail -n1 | cut --delimiter=" " --fields=8);
  percentage=$(amixer get Master | tail -n1 | cut --delimiter=" " --fields=7 | grep -oe "[0-9]*");
  case $vstate in
    ("[on]") echo "🔔 $percentage%";;
    ("[off]") echo "🔕";;
  esac
}

printdate(){
  t=$(date '+%H:%M %a %Y.%m.%d');
  echo "🗓️ $t" 
}

printwifi(){
  ssid=$(iw dev wlp8s0 link | grep "SSID" | cut --delimiter=' ' --fields=2)
  if [ -z $ssid ]
  then
    echo "🚫"
  else
    echo "🛜 $ssid"
  fi
}

xsetroot -name "|$(printdate)| |$(printwifi)| |$(printbat)| |$(printvolume)|"
