#!/bin/sh
picomconf="$HOME/.config/picom/picom.conf"

_thisdir=$(cd $(dirname $0);pwd)

settings() {
  [ $1 ] && sleep $1
  xmodmap -e "keycode 135 = Super_R" &
  xautolock -time 10 -locker slock &
}

daemons() {
  [ $1 ] && sleep $1
  [ -d $HOME/log ] || mkdir $HOME/log
  dwmstatusbar > $HOME/log/dwmstatusbar.log 2>&1 &
  picom -b --config $picomconf &
  dunst -b > $HOME/log/dunst.log 2>&1 &
  xbanish &
  fcitx5 -d > $HOME/log/fcitx5.log 2>&1 &
  goldendict &
  redshift -v > $HOME/log/redshift.log 2>&1 &
  flameshot &
}

cron() {
  [ $1 ] && sleep $1
  while true
  do
    feh --randomize --bg-fill $wallpapers/*.png
    sleep 5m
  done
}

settings 2 &
daemons &
cron &
