#!/bin/sh
_thisdir=$(cd $(dirname $0); pwd)

settings() {
    [ $1 ] && sleep $1

    [ -x "$(which xmodmap)" ] \
        && xmodmap -e "keycode 135 = Super_R" &

    [ -x "$(which setxkbmap)" ] \
        && setxkbmap -option "caps:ctrl_modifier" &

    # [ -x "$(which xautolock)" -a '$(which slock)' ] \
    #     && xautolock -time 10 -locker slock &
}

daemons() {
    [ $1 ] && sleep $1

    [ -x "$(which picom)" ] \
        && picom -b &

    [ -x "$(which dunst)" ] \
        && dunst &

    [ -x "$(which xbanish)" ] \
        && xbanish &

    [ -x "$(which fcitx5)" ] \
        && fcitx5 -d 2> /dev/null &

    [ -x "$(which goldendict)" ] \
        && goldendict 2> /dev/null &

    [ -x "$(which redshift)" ] \
        && redshift 2> /dev/null &

    [ -x "$(which flameshot)" ] \
        && flameshot 2> /dev/null &

    [ -x "$(which nm-applet)" ] && \
        nm-applet &
}

cron() {
    [ $1 ] && sleep $1

    i=0
    while true
    do
        [ -x "$(which feh)" ] && [ $((i % 300)) -eq 0 ] \
            && feh --randomize --bg-fill $wallpapers/*.png

        [ -x "$(which dwm-statusbar)" ] && [ $((i % 2)) -eq 0 ] \
            && dwm-statusbar

        sleep 2; i=$((i + 2))
    done
}

settings 2 &
daemons &
cron &
