#!/bin/sh
if pidof trayer-srg > /dev/null
then killall trayer-srg
else 
    trayer-srg\
        --edge left\
        --transparent on\
        --widthtype request\
        --align center\
        --padding 2\
        --margin 2 &
fi
